spring.application.name=cors
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:33061


spring.datasource.username=root
spring.datasource.password=test1234

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=krumin8384@gmail.com
spring.mail.password=wdxswgjmbllxsydx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# server.port=8081
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

mybatis.mapper-locations=classpath:/mappers/**/*.xml


server.tomcat.max-parameter-count=100
server.tomcat.max-swallow-size=10MB

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=50MB


file.upload-dir=${user.home}/Desktop/upload/

custom.property.kakao-client-id=4f06c4d97874ff86be3d1acdd4846b17
custom.property.kakao-redirect-uri=http://localhost:8080/login/kakao
custom.property.naver-client-id=VzFkhxdtnv6_Z7FlsP5N
custom.property.naver-client-secret=CA2cnKxJtJ
custom.property.naver-redirect-uri=http://localhost:8080/login/naver